### ISSUE TITLE
GPU already preallocated at start of processing - problem still present

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#11]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1122

**Comment by brucehoff** [comment]
Here's what might be another case of this problem:
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1048

**Comment by tschaffter** [comment]
An option could be to use `nvidia-smi -r -i <gpu index>`.

[root@vm ~]# nvidia-smi -r -i 0
Unable to reset this GPU because it's being used by some other process (e.g. CUDA application, graphics application like X server, monitoring application like other instance of nvidia-smi). Please first kill all processes using this GPU and all compute applications running in the system (even when they are running on other GPUs) and then try to reset the GPU again.
Terminating early due to previous errors.
[root@vm ~]# nvidia-smi
Fri Oct 28 21:24:33 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.99     Driver Version: 352.99         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 0000:83:00.0     Off |                    0 |
| N/A   30C    P8    27W / 149W |     55MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 0000:84:00.0     Off |                    0 |
| N/A   30C    P8    28W / 149W |     55MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 0000:87:00.0     Off |                    0 |
| N/A   31C    P8    27W / 149W |     55MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 0000:88:00.0     Off |                    0 |
| N/A   30C    P8    27W / 149W |     55MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by brucehoff** [comment]
I found some discussions on line about memory leaks, saying that upgrading to driver version 364.12 or 364.35 solved the problem.  We are using 352.99.

**Comment by brucehoff** [comment]
Here's the dashboard of the referenced submissions:

${leaderboard?path=%2Fevaluation%2Fsubmission%2Fquery%3Fquery%3Dselect%2B%2A%2Bfrom%2Bevaluation%5F7213944%2Bwhere%2BSUBMITTER%253D%253D%25223346508%2522&paging=true&queryTableResults=true&showIfLoggedInOnly=false&pageSize=100&showRowNumber=false&jsonResultsKeyName=rows&columnConfig0=none%2CSUBMISSION ID%2CobjectId%3B%2CNONE&columnConfig1=none%2C%2Cstatus%3B%2CNONE&columnConfig2=none%2CStatus Description%2CSTATUS%5FDESCRIPTION%3B%2CNONE&columnConfig3=userid%2C%2CuserId%3B%2CNONE&columnConfig4=none%2C%2CteamId%3B%2CNONE&columnConfig5=none%2C%2CWORKER%5FID%3B%2CNONE&columnConfig6=epochdate%2C%2CcreatedOn%3B%2CNONE&columnConfig7=epochdate%2C%2CTRAINING%5FSTARTED%3B%2CNONE&columnConfig8=epochdate%2C%2CmodifiedOn%3B%2CNONE&columnConfig9=synapseid%2C%2CentityId%3B%2CNONE&columnConfig10=none%2C%2CSUBMISSION%5FFOLDER%3B%2CNONE&columnConfig11=none%2C%2CrepositoryName%3B%2CNONE&columnConfig12=none%2C%2CMODEL%5FSTATE%5FENTITY%5FID%3B%2CNONE}

**Comment by tschaffter** [comment]
How do we use the code that you copied pasted?

**Comment by brucehoff** [comment]
I found an example of the reported bug:  On bm17 'agent 1' (controlling GPUs 0,1) is running but 'agent 2' (controlling GPUs 2,3) is stopped, yet GPU 3 still has memory allocated.  

I found the problem, in my start up script.  I have:

AGENT_INDEX=$2
if [[ AGENT_INDEX = 1 ]]; then
	GPUS=/dev/nvidia0,/dev/nvidia1
	AGENT_CPUS="0"
	CPUS="1-22"
else
	GPUS=/dev/nvidia2,/dev/nvidia3
	AGENT_CPUS="24"
	CPUS="25-46"
fi

But the second line should be 
if [[ ${AGENT_INDEX} = 1 ]]; then

**Comment by brucehoff** [comment]
> How do we use the code that you copied pasted?
Create and edit any Synapse wiki page, copy the content into the wiki, and save.

**Comment by brucehoff** [comment]
The start up script and running agents have been updated.
