### ISSUE TITLE
shutdown hook doesn't work right

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#155]
The server agent has a 'shut down hook' which is intended to let the agent finish its current round of checking submission progress before shutting down.  But it doesn't work right.  I tried:
docker stop -t 60 bm02-1-train
(give the agent 60 sec to shut down before killing it) but it didn't work.  It hung for 60 sec and then was killed.   The shut down hook prints "Shut down signal received." to the logs but this was never printed.

**Comment by zimingd** [comment]
The issue was that `docker stop` only sends the termination signal to the process in the container with process id of 1.
In the last line of the Dockerfile we have the command:
CMD mvn exec:java

If we run the container with this command, docker will use /bin/sh to run `mvn exec:java` as a child process.
I used `docker exec <running container id> ps -ef` to verify this.

Unfortunately, /bin/sh does not forward the signal to its child processes so there is no way for Java to shutdown gracefully.

However if we instead set the last line of the Dockerfile as
CMD exec mvn exec:java

Then instead of forking a child process, the exec() system call would replace the bin/sh/ process with that of 'mvn exec:java', thus giving Java a process id of 1 and allowing it to receive the shutdown signal.

**Comment by brucehoff** [comment]
Works great now!
