### ISSUE TITLE
Queued submission do not appear in the dashboard

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#190]
This is a know issue but I didn't find a ticket for it.

I submitted 5 times the same submission file within 1 minute. Submission appeared in the dashboard only when they started running. I would expect to see immediately all five submissions. This feedback is important to the participants so that they get visually a confirmation that they have successfully submitted a task.

**Comment by brucehoff** [comment]
The issue will go away once this other one is done:
https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/issues/143
Kindly verify this is the case once the cited issue is closed.

**Comment by brucehoff** [comment]
This is the same as #208

**Comment by thomasyu888** [comment]
Has this been implemented?

**Comment by brucehoff** [comment]
> Has this been implemented?

Yes, in particular the filter used to show the personal dashboard now uses data immediately available upon submission rather than data created during validation or when the submission starts running.  This allows submissions to appear in the dashboard right away.  

Would be great if you would confirm the feature works as requested before closing this issue.

**Comment by thomasyu888** [comment]
I confirm that I can see submissions before they start running.
