### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/trainingData/cmkg906a.dcm'

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#215]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1206

**Comment by tschaffter** [comment]
@brucehoff The image cmkg906a.dcm reported as missing on the training express lane by cmkg906a.dcm is there.
```
[root@bm04 ~]# find /data/data -name cmkg906a.dcm
/data/data/images/training/cmkg906a.dcm
[root@bm07 ~]# find /data/data -name cmkg906a.dcm
/data/data/images/training/cmkg906a.dcm
[root@bm08 data]# find /data/data -name cmkg906a.dcm
/data/data/images/training/cmkg906a.dcm
[root@bm09 ~]# find /data/data -name cmkg906a.dcm
/data/data/images/training/cmkg906a.dcm
```

I'm not sure I remember correctly, but is it possible that you told me that you are not mounting /trainingData if a preprocessing step is specified? /trainingData should always be mounted during training because the fact that participants preprocess the data doesn't mean that they don't need the original anymore.

**Comment by brucehoff** [comment]
> /trainingData should always be mounted during training because the fact that participants preprocess the data doesn't mean that they don't need the original anymore.

That's a good suggestion and easily implemented.

**Comment by tschaffter** [comment]
@brucehoff Can you implement the fix now and confirm that it's done? I'll then take care of testing it and answer to the participant.

**Comment by tschaffter** [comment]
@brucehoff You can close this thread if /trainingData is now systematically mounted during training.
