### ISSUE TITLE
Setup training submission queue for each Dry Run machine

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#258]
The goal is to standardize the training procedure for the Dry Run teams. Each team should have exclusive access to its own Synapse training submission queue.

- bm11: IBM Australia
- bm12: IBM Haifa
- bm13: Darvin

/trainingData/\*.dcm -> /data/data/dm-challenge-dcm/training/\*.dcm
/metadata/training_images_crosswalk.tsv -> /data/data/metadata/training_images_crosswalk.tsv
/metadata/training_exams_metadata.tsv -> /data/data/metadata/training_exams_metadata.tsv
/preprocessedData -> /data/dataset0
/modelState -> /data/model0
/scratch -> /data/scratch0

**Comment by tschaffter** [comment]
Filesystem ready.
Sysdig and nvml-statsd running.

**Comment by brucehoff** [comment]
@tschaffter:  I felt strongly about having the 'dry run team' use Synapse submission queues for the ten-split analysis because I felt it would parallelize and greatly accelerate the analysis.  I wonder if the team continues to be best supported by asking them to use the Synapse submission queues when working on a single split.  Do they feel that it will be?

**Comment by tschaffter** [comment]
I want the team to package their methods in a Docker container that work on the training and express lane. Instead of setting up submission queue, I'll give them a command similar to the one you use to mount the input data correctly in their container so that they can run the docker locally without using Synapse. We can discuss how to score their method when it will be required.
