### ISSUE TITLE
Link for QUEUE status

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#284]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1277

**Comment by tschaffter** [comment]
@thomasyu888 The link that you included redirects to the dashboard of the Express Lane. I guess that the participant is mainly interested in the dashboard for the Challenge. Currently only the Challenge training dashboard can be seen on the page "Submiting Models" (if the participant has made at least one submission otherwise the table is invisible because the header would not even be shown). Bruce will ultimately create more dashboard pages (there is another GitHub issue for that).

**Comment by thomasyu888** [comment]
Ahh I see. Thanks for clarifying
