### ISSUE TITLE
The available space of /modelState directory

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#289]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1280

**Comment by tschaffter** [comment]
The model of the participant is larger than the size of `/modelState` (about 4 GB vs 1 GB `/modelState`). He is asking if we plan to increase `/modelState`.

Using the current implementation, one trick that I can imagine is for him to do pre-processing + training in a pre-processing container so that he has writable access to the persistent storage `/preprocessedData` where he can save his model. Each day, he can then submit a submission file that refers to the pre-processed data and use the training container to download one slice of its model. This is not the way we intend the participants to use the system and its a bit awkward to do. For these reasons, I'm not sure we should suggest this solution to the participant.

The general questions is how to allow participants to retrieve large models when they are allow in principle to download 1 GB/day.

1. The simplest solution would be to allow participants to immediately be able to download all the data they are allowed since day 1. However there are risks that participants inadvertently download all their quota and can't work any more. Also participants can be used to quickly steal data using multiple participant accounts. Also, this may go against the agreement from Group Health of 1 GB / day / participant thought this can be interpreted as X GB / round / participant. A modification of 1. could be to add a limits, for example 5 GB / day. 

2. Another solution could be to allow participant to reclaim unused data within the past X days (e.g. 5 days). This would allow participant to retrieve up to X GB models if they have not consumed data during the past X days. X could be initially set to 5. In principle, I would not change the rules during a round to avoid confusing the participants.

@brucehoff What are your thoughts and what would you answer to the questions of the participant?

**Comment by tschaffter** [comment]
Regarding a modification of the data quota, I would reply to the participant that we may change the rules for the second Round, but not for this round.

**Comment by brucehoff** [comment]
When we set the limit on the model state size we had two considerations, (1) the data leakage risk and (2) the expected size of the model state.  IIRC, for (2) we expected a typical model state to be around 100MB and setting it to 1GB ensured that the limit didn't affect participants who used the volume as intended.   So I'm wondering what's in this participant's 4GB.  Is it the state of a certain popular framework?  Does he have multiple checkpoints?  We should decide whether we have correctly assessed the typical model state size or whether participants will frequently need a larger size.  If the latter, we should consider increasing it.

**Comment by tschaffter** [comment]
That's excellent points that you are bringing here. I'll answer the participant, first to get more information about their model, and then we may look for relatively simple solutions or future improvements in round 2+.

**Comment by tschaffter** [comment]
@thomasyu888 Please also avoid copying/pasting large chunk of the documentation in the threads. Instead prefer a link that redirect to the documentation. If someone in the future follows the link, he will find there the latest version of the documentation.

**Comment by brucehoff** [comment]
Per #488 we will allow larger models without increasing the 'data leak risk' by letting users aggregate their quota (say, download 5 GB each 5 days).
