### ISSUE TITLE
Submission stucked (11 hours) on EVALUATION_IN_PROGRESS

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#332]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1327

**Comment by thomasyu888** [comment]
Is this the right answer for this question:

You will want to use the non express lanes for the actual submission.  Unfortunately, once you do preprocessing on one machine, what happens is that the training also has to happen on that machine.

**Comment by tschaffter** [comment]
The submission ID communicated by the participant tells us whether he submitted to the Express Lane or Challenge Lane. For a HelloWorld example he should indeed use the Express Lane. Ask him if he is doing meaningful pre-processing in his HelloWorld example. Redirect him to the dashboard to monitor his submission (express lane, challenge lane).

@brucehoff Any advances on the creation of the remaining dashboard pages?

Tom, you can also ask him to check his log. Does he see any progress on them? If no, there is a problem with the system. If no, he is stuck in EVALUATION because it takes time to do the pre-processing.

**Comment by brucehoff** [comment]
> Is this the right answer for this question:

He asked several questions, and we should probably answer each one

> I am wondering in this case, what's the best way to monitor my submission. 

The best way is the dashboard in Sect. 3.6 (scroll down to the table in the "Time Quota" section).  (For the express lane it's Sect. 3.6.1.)

> Did I do something wrong that makes my submission stuck?

No.  

> In addition, I received results in 5 mins after submitted through the Training Express Lane. Am I supposed to use the express lane for all my training?

No.  The 'express lane' only gives you a quick indication of whether your code is correct error free.  The a actual computational results are not meaningful.

Thomas says:
> For a HelloWorld example he should indeed use the Express Lane

That is a very good point:  For a quick test of end-to-end functionality, the express lane is the right tool to use.

> Does he see any progress on them? If no, there is a problem with the system.

I think the most definitive way to check for a problem in the system is to look at the "Last Updated" column in the dashboard.  It should always show a time stamp that's just a minute or so old.  If it hasn't been updated in hours then our server agent has stopped.  (We have an open issue to create an alarm based on such a check.  The server agent already alerts us by sending an email when it's about to quit due to an anomalous condition.)

> Any advances on the creation of the remaining dashboard pages?

That is still pending.
