### ISSUE TITLE
Create submission queues for Dry Run teams

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#398]
Hi Bruce,

IBM Australia has issue running their software locally on bm11. Their method is currently package in a docker container and runs fine on the express lane. I proposed once again that we create a training submission queue exclusive to them that target their machine (bm11). Can we do that?

Also, I think that we are running one agent on one of the inference machines that accept access exclusively from the Dry Run teams. Maybe I don't have access to it but I don't think that I see it when trying to submit a file.

Aside the official submission queues, we have:
- DM smoke test
- Evaluation Leaderboard Testing 2

Can you remind me what they are used for? Before closing this ticket, we should have the following queues:
- DM Dry Run Model Training (IBM Australia)
- DM Dry Run Model Training (IBM Haifa)
- DM Dry Run Model Training (Stanford)
- DM Dry Run Prediction - Sub-Challenge 1
- DM Dry Run Prediction - Sub-Challenge 2

Dry Run machines have the training set file set up the same way that on the Challenge machines. Please let me know if you have any questions.

Thanks!

**Comment by tschaffter** [comment]
Following today's Dry Run call, IBM Haifa is also interested in having a submission queue that redirect to their machine (bm12).

**Comment by brucehoff** [comment]
@tschaffter discussed this today.  Our thought is to create submission queues for training and scoring (with the priority being to set up the training queues).  For scoring, we can configure challenge scoring machine(s) to service multiple queues. Thus internal teams can have private queues without requiring that we provide dedicated machines for (infrequent) scoring.

**Comment by brucehoff** [comment]
The following Synapse submission queues are now available:
DM TRAINING HAIFA - This is available just to members of the Synapse "IBM Haifa" group.  Submissions sent to this queue are run on the dedicated IBM Soflayer GPU server "bm12".

DM TRAINING IBM AUSTRALIA - This is available just to members of the Synapse "IBM Australia" group.  Submissions sent to this queue are run on the dedicated IBM Soflayer GPU server "bm11".

DM TRAINING STANFORD - This is available just to Darvin Yi.  Submissions sent to this queue are run on the dedicated IBM Soflayer GPU server "bm13".

DM DRY RUN SCORING SC-1 , DM DRY RUN SCORING SC-2 - These are available to the entire internal group.  Submissions are run on the same machines used to run inference submissions for the challenge in general, but since they are in a separate queue they will not appear on the open challenge's leaderboard.

The contents of the five submission queues can be viewed on this page:
https://www.synapse.org/#!Synapse:syn5644795/wiki/402564
