### ISSUE TITLE
Submissions waiting in VALIDATED STATE 

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#485]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1519

**Comment by tschaffter** [comment]
@brucehoff @thomasyu888 One of the participant is Tom about the activity on the cloud. This thread could be closed after giving him this information.

**Comment by thomasyu888** [comment]
Is any way you can post an approximate waiting time, or post how many jobs are waiting in line? This could be nice to have so that people don't continually post about how their submission hasn't run yet.

**Comment by brucehoff** [comment]
> Is any way you can post an approximate waiting time

How would one compute this?

**Comment by thomasyu888** [comment]
Well not the approximate waiting time, but we could potentially show how many jobs are waiting in line with a query to the evaluation queue?

**Comment by tschaffter** [comment]
> I'm not sure if thats something we want to expose.
A generic queue to be process before a submission is not a solution. There is a "local" and "global" dimension to the problem. A submission can have to wait to run because the machine on which his pre-processed data are has other local submissions to run first. If the machine is not bind by the pre-processed data - there is still an "inconsistency" in the framework where a submission with a new pre-processing container could run anywhere but is current still linked to the machine where deprecated pre-processed data where saved in the past - then the global queue applies.

If we can't come up with a simple solution, we shouldn't expose the requested information.

**Comment by brucehoff** [comment]
> If we can't come up with a simple solution, we shouldn't expose the requested information.

Agreed.  I would say, if we don't have a strict order in which we process submissions then we can't say how long the queue is.  We would risk having the queue appear to get *longer* or to get shorter for one participant but not for another, triggering a rash of unhappy posts on our forum.
