### ISSUE TITLE
Check whether servers are 'slowing down'

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#516]
See comment on this thread: https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1536

> I am concluding that the Express Training queue has slowed down significantly compared to five days ago, and that
this is not transient behavior, but completely reproducible.
I have a workaround, so strictly speaking you don't need to investigate further on my behalf. Thank you for offering. I'd say
however that there is an issue in the system and it would be advantageous to explain it. Most importantly, since we don't
know the cause, it is possible that it may affect the "full" queues. I.e., all queues might be running slower, not just express

**Comment by tschaffter** [comment]
We are closing the issue because no evidence have been reported that some machines have slowed down.

Starting from Round 3, the prefix printed in front of every line in the log file now includes date and time information. Next time someone reports that a machine is "slowing down", the idea is to run the same submission on a test machine and compare the evolution of the time information in the two log files.
