### ISSUE TITLE
More environment variables?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#535]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1575

**Comment by thomasyu888** [comment]
Participant has a suggestion

**Comment by tschaffter** [comment]
I currently don't see the usage for the two environment variables suggested. Answered to OP to get additional information.

**Comment by thomasyu888** [comment]
He responded, but not sure if we need to respond to it

**Comment by tschaffter** [comment]
@brucehoff The problem of the OP is that his method can not process 1% of the training set in 20 minutes. In a naive scenario, a method that fully processes 1% of the training set in 20 minutes would takes 33 hours to process the entire training set, which is reasonable. We still want to keep a 20 minutes (or 30 minutes on the AWS servers) so that participants can test quickly their method.

As suggested by OP, I think that the best solution for him and other is to define an environmental variable that inform that the method is running on the Express Lane. On alternative and maybe more generic approach is to specify the variable WALLTIME (seconds or minutes) to specify that the container has a time constrain. Could this variable be easily put in place?

**Comment by brucehoff** [comment]
> We still want to keep a 20 minutes (or 30 minutes on the AWS servers) so that participants can test quickly their method.
Yes, the cut-off is currently 30 minutes, on the AWS servers.

>  I think that the best solution for him and other is to define an environmental variable that inform that the method is running on the Express Lane.
They can 'bake' into their container a parameter that says whether they are running on the express lane.  It's a little inconvenient, but it ensures they are not 'blocked', waiting for us to change our pipeline.

**Comment by tschaffter** [comment]
@brucehoff That's what he is currently doing, i.e. a hack that relies on the difference between the Express Lane and Challenge architecture. However, since we are going to use his container in the future (Collaborative Phase and later released open-source), we want to have a better control the situation. That is, we don't want his method to enter into the "special express lane mode" because the dataset is less than a given size, for example. That's way I think the most generic way to handle this is to define a WALLTIME variable. Knowing the size of the dataset in front of him and the provided wall time, a method could adjust some of its parameter to ensure that it completes before hitting the wall time.

Could this variable be easily put in place?

**Comment by brucehoff** [comment]
> we don't want his method to enter into the "special express lane mode" because the dataset is less than a given size, for example. 


Yes, that is a good point.

> Could this variable be easily put in place?

It's not very hard to add an environment variable to the user's container and to set it differently between express lane / leaderboard.

> hat's way I think the most generic way to handle this is to define a WALLTIME variable.

I'm not clear on what 'walltime' is.  Can you please clarify?

**Comment by tschaffter** [comment]
> I'm not clear on what 'walltime' is. Can you please clarify?

A wall time is the maximum amount of time that a job can run on a cluster. The wall time on the Express Lane is 20 minutes.

**Comment by tschaffter** [comment]
@brucehoff Can we put the WALLTIME environmental variable in place?

**Comment by brucehoff** [comment]
@tschaffter When we start a job we don't know how long it has to run, so we can't pass that in as a parameter.  We *could* add the parameters that OP requests.

**Comment by tschaffter** [comment]
@brucehoff We do on the Express Lane. You can set WALLTIME to Long.MAX_VALUE on the Challenge machines (optional: have the agents query the system for the remaining time quota and update the environment variable). This solves elegantly the problem of the OP.

**Comment by brucehoff** [comment]
Sorry, but I am still unclear regarding the meaning of WALLTIME.  I found

> Wall-clock time is the time that a clock on the wall (or a stopwatch in hand) would measure as having elapsed between the start of the process and 'now'.

http://stackoverflow.com/questions/7335920/what-specifically-are-wall-clock-time-user-cpu-time-and-system-cpu-time-in-uni

I also found a reference to "walltime limit" which is the quota of time allocated to run a job

https://acf.ku.edu/wiki/index.php/Cluster_Jobs_Submission_Guide


It seems that the phrase "walltime limit" is sometimes shortened to "walltime" and I *think* this is the meaning you are using for the word.  We do indeed impose a "walltime limit" on each process running on the express lane.  However we do not have such a limit on the leaderboard training queue.  Instead we have a limit on the team.  The difference comes into play when a team is running multiple submissions.  The effective "walltime" for a process depends on other running processes.  If we pass a value called "walltime" (our best guess) and the participant writes his code to make decisions based on that value, then things will break when the value is inaccurate.

I'd rather be safe and just pass a parameter like EXPRESS_LANE=TRUE or FALSE.

**Comment by brucehoff** [comment]
We agreed to add WALLTIME on the express lane and to leave the environment variable out on the leaderboard.

**Comment by tschaffter** [comment]
@brucehoff There is still an issue with the decision of not applying the variable to all the machines. If we only expose it to the Express Lane machines, participant will use its presence as a boolean variable to run a different script on the Express Lane using prior knowledge about the configuration of the Express Lane. The problem is that the value of the variable (in minutes or seconds) loose its meaning if a container perform a test on its presence only. This is a minor issue and not worth spending too much time on that, but I'm for providing systematically the variable and set it to Long.MAX_VALUE (2^64-1) on the challenge machines if there is nothing that justify not to do it, for example a potential error. The correct usage of the wall time would be to run a timer inside the code and make sure the method returns successfully when it sees that it's running our of time.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/927d4b527220756318e884971c0df29a490fdeb1
