### ISSUE TITLE
Cancel button in inference submission queue

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#559]
Several times we have been requested to cancel a queued submission to the inference queue.  We should add a cancel button so participants can do this themselves.

**Comment by tschaffter** [comment]
@brucehoff Some thinking. I'm wondering if we should put a limit to this feature. If we don't, participants will not bother about sending a robust and well tested container as it doesn't cost them anything to cancel one. However, we would loose precious computation time on the Inference machines if a running submission is interrupted in the middle because the participant think that he can perform better. This may also have the negative effect of postponing the submissions later towards the end of the round, with the risk that a team does not submit at least one valid submission on time. Also, participants should distribute their 3 submissions uniformly across the duration of the round to get feedback on how well their methods performed.

Possible actions:
- Do not allow to stop a running inference method: prevents to remove the submission if the team think that they can do better. If they remark that there is an issue, they will better check their container next time. Of course, it's a bit silly to keep processing this submission if the team knows that the output is not going to be usable.
- Limit the number of times that a team can cancel an inference submission (5 times/round). This will help keeping in their mind that they need to carefully check their submission before sending it.
- Do nothing if we consider that we have sufficient computational power or if we are only tight on computational resources at the end of a Round when every team submits.

**Comment by brucehoff** [comment]
> However, we would loose precious computation time on the Inference machines if a running submission is interrupted in the middle because the participant think that he can perform better.

Yes, you are right.

> Do not allow to stop a running inference method

A simple approach here is to let someone cancel a *queued* submission but not a *running* submission.  This allows them to cancel an accidentally submitted job shortly after creating it, but not to cancel one that has consumed computational resources already.

**Comment by tschaffter** [comment]
> This allows them to cancel an accidentally submitted job shortly after creating it, but not to cancel one that has consumed computational resources already.

I agree that they should be able to cancel a pending submission anytime. We could however save computational resources if they identify that the submission will not produce usable results or is going to crash when a specific condition is met (not worth running something 5 days if it doesn't help the Challenge). However if they keep in mind that they need to test their container first, the problem would disappear. So let's go as you suggested and communicate (newsletter, forum) to remind them to test thoroughly their submission first as they contact us to cancel one of their running submissions.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/8289b043a05589bcd984a6d25ff523636eaf588a

Remaining tasks:
- add cancel button column to inference dashboards
- smoke test new feature
- ask for wiki pages to be mirrored
- publicize the feature
