### ISSUE TITLE
Implement size limit on returned data

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/DigitalMammographyChallenge#6]
Participants get log files back continuously while their training model runs and their model state back when their model terminates.  The limit is 1 GB / team / day for both logs and model state.  

While a submission runs the personal dashboard will be annotated with:
- bytes used in current submission (i.e. size of log file returned)
- bytes remaining for the day

If the log file reaches 1GB then the system will stop uploading to Synapse.  An email notification will also be sent so that participants may choose to halt their submission and retain their time quota.

**Comment by brucehoff** [comment]
I'm changing the milestone from "Bare Minimum..." to "Open leaderboard..."  The remaining tasks are:
1) Send notification if log file exceeded.  (Since the overall limit is now 1GB this probably won't happen.)
2) Annotation submissions with bytes used / bytes remaining. (Again this will be the bytes used for the returned log files, which doesn't tell them whether their model state is going over the limit.)

**Comment by tschaffter** [comment]
@brucehoff Can we close this issue?

**Comment by brucehoff** [comment]
> @brucehoff Can we close this issue?
No, still need to do the two secondary items listed above.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/ChallengeDockerAgent/commit/c6d6e8bd2653e861cf3616b5171e8afd071ab317
