### ISSUE TITLE
Sub-challange 1 Express Lane shows very different score for the SAME model

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#609]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1678

**Comment by tschaffter** [comment]
@thomasyu888 Can you check that the two submissions refer to the same submission file or the same containers? Moreover, has the evaluation script been changed?

Another recent change is that the Express Lane Inference machine has been moved recently to another machine. However, I don't see any issue with the dataset. If the files where different, the scoring script would throw an error because the subject IDs are different (or report that some of them are missing).

**Comment by thomasyu888** [comment]
The evaluation script has not been changed at all.  I will look into this
