### ISSUE TITLE
Cancelling submissions

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#635]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1701

**Comment by brucehoff** [comment]
Responded on the forum.

**Comment by brucehoff** [comment]
@tschaffter I am addressing the canceled submission issue on this thread, but could you please address another point that OP brought up in his latest post:

>Finally, there is a reason why we submitted over 3 submissions:
because of the following claim in the Wiki:
This also implies that the subjects in the scoring set must be
processed sequentially and not using multiple threads.
This is not true: we now know that the multi-threaded submissions work
perfectly fine. But we did not know that before actually
trying. Therefore we had to submit both single-thread and
multiple-thread versions - exact same models, just different number of
threads - not knowing if the multi-threaded ones will finish at
all. We would appreciate if this instruction is corrected/clarified.

I'm guessing you, @tschaffter, are the author.  If not, let me know.

**Comment by tschaffter** [comment]
@brucehoff The link to the thread that includes the above quote would have been useful. If I can retrieve it, I'll answer to the OP. Meanwhile, I've corrected the documentation on the staging wiki. I'll ask Tom to update it after our 2 pm Hangouts. For now I'm closing this ticket because there is no issue remaining regarding it.
