### ISSUE TITLE
Express lane seriously lags

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/DigitalMammographyChallenge#701]
https://www.synapse.org/#!Synapse:syn4224222/discussion/threadId=1822

**Comment by tschaffter** [comment]
I think we mentioned that we would include the time stamp in the prefix of each log line. The log reported by the participant doesn't include it.

**Comment by tschaffter** [comment]
I asked the user to run an experiment. Difficult to draw conclusion has this issue may only affect submissions that use GPUs, for instance. The user mentions that the problem also affects SC2 Express Lane Inference so maybe it's a general issue with the machines OR the problem is in his submissions (I asked hi to do an experiment to rule out that possibility). Let's wait on his answer and if the issue is an our side, we will start investigating.

**Comment by tschaffter** [comment]
@brucehoff Yaroslav Nikulin is submitting the entityId syn7540712 to the Express Lane SC1. I don't have the permission to look at the content. I guess that this refers to a submission file. syn7540712 run successfully on before today but today he submitted syn7540712 several times that got timed out. Since the ID of the file doesn't change if the content change, can you check whether he is effectively submitting the same container?

**Comment by tschaffter** [comment]
Yaroslav Nikulin timed out on both Express Lane inference machines p28x02 and p28x14.

**Comment by brucehoff** [comment]
@tschaffter, you say

> Since the ID of the file doesn't change if the content change

That's not actually true.  One Synapse ID (synXXXX) can refer to a series of revisions.  If the entity is a File, then the unique content is referenced by a Synapse ID and a version number.  In this case though the entity is a Docker repository, the content of which is uniquely referenced by a commit, including a SHA256 digest.  The repository is `docker.synapse.org/syn7540399/dm_challenge` and the digest seems to be different for each submission.  There are at least seven submissions of the repository, each with a different digest.

**Comment by tschaffter** [comment]
@brucehoff Yaroslav copied/pasted log that doesn't include the timestamp. Can you remind me how to visualize the log of any past submission? Ideally place the instructions here:

https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/wiki/Getting-the-log-of-a-submission

To rerun a pre-processing/training/inference submission, I tried to use your nice python script [lookupSubmission.py](https://github.com/Sage-Bionetworks/DigitalMammographyChallenge/blob/master/lookupSubmission.py) to get the repository name and digest of the container corresponding to a submission ID. However, it doesn't seem to implement the case where the submission ID refers to an inference submission. Could you upgrade the script so that it also return the repository name and digest of the corresponding container?

**Comment by brucehoff** [comment]
> Ideally place the instructions here:

Done.  Please let me know if this doesn't suffice.

> Could you upgrade the script so that it also return the repository name and digest of the corresponding container?

Done.

**Comment by tschaffter** [comment]
The Express Lane is now closed.
We have more detailed data from other "lag" reports. We may investigate them at a later time if we are interested/need to.
