### ISSUE TITLE
Mt Sinai dataset issue

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/DigitalMammographyChallenge#886]
Yuanfang emailed me about her Mt Sinai submissions, you can see them here https://www.synapse.org/#!Synapse:syn9935146/wiki/450922 under MSSM dataset.

It is on machine bm12.  I checked the logs of both files, did a grep and wc -l on the word "finished":
`There are 23022 for 9624985 and 12220 for 9625095`

Are there more than 10K individuals in the test set?  Yuanfang is concerned because she thought this was a small dataset, but its taking a long time to run.

**Comment by tschaffter** [comment]
@thomasyu888 Are we talking about an inference submission?

**Comment by tschaffter** [comment]
On bm12:

```
[root@bm12 metadata]# wc -l /data/data/mssm-split2/leaderboard/metadata/exams_metadata.tsv
636 /data/data/mssm-split2/leaderboard/metadata/exams_metadata.tsv
[root@bm12 metadata]# wc -l /data/data/mssm-split2/leaderboard/metadata/images_crosswalk.tsv 
1317 /data/data/mssm-split2/leaderboard/metadata/images_crosswalk.tsv
```
As you can see, there are no data for 10K or so individuals.

@thomasyu888:

1. Check that you are mounting the correct metadata files for the Mount Sinai submission queues. Make sure you are not mixing Group Health and Mount Sinai files.
2. Run SC2 baseline method on this machine and show Yuanfang that the method run successfully.

Thanks!

**Comment by brucehoff** [comment]
@tschaffter:
Tom Yu explained the issue of needing to support multiple data sets.  The server-side agent is not designed to do this.  In order to get a quick and reliable system in place I would like to propose the following:  Let's add one server per additional dataset (beyond the original Group Health dataset) to process all the inference submissions for that data set.  E.g., there would be one server for the MSSM inference data set, one server for the Karolinska data set.  All teams would share the queue for each of these dataset-dedicated machines.  As with other machines, each of these servers could process two inference submissions at a time.  If a bottleneck forms due to demand for a dataset, we can scale hardware as needed.

Again, this suggestion stems from the desire to put a solution in place quickly and reliably (avoiding problems such as the one that triggered this issue).  It's admittedly less elegant than having each server support 'n' datasets, but such a software change would take additional time.

**Comment by tschaffter** [comment]
@brucehoff @thomasyu888 I didn't understand that issue until now. Tom told me that he successfully run a baseline method on Mount Sinai inference dataset. To make sure, does that mean that at the time of the test the machine was not able to process a second inference submission on the Group Health dataset?

> Again, this suggestion stems from the desire to put a solution in place quickly and reliably (avoiding problems such as the one that triggered this issue).

What about the following to go around the issue of wasting computational power and having participants being slowed down by the submission of other participants?

- Add a parameter `dataset=` in the inference submission file. Possible values are "grouphealth" and "mountsinai". If not specified, expose the Group Health dataset.

This should take only a few lines of codes to put in place. Anyway, I let you and Tom take the lead on that issue as you know better than me what is and is not feasible. Please communicate with the participants regarding any changes you are requiring from them.

**Comment by thomasyu888** [comment]
@tschaffter I thought I ran a successful baseline method, but I actually didn't.  The Mt Sinai queues are pointing to the group health data. Sorry about that.

**Comment by thomasyu888** [comment]
This has been implemented. https://www.synapse.org/#!Synapse:syn9935146/wiki/453665

**Comment by tschaffter** [comment]
@thomasyu888 What exactly has been implemented?
